### ISSUE TITLE
Add Rococo

### ISSUE THREAD

**Issue by evilrobot-01** [stiiifff/trappist-extra#21]
It would be great to add the Rococo relay chain and a few other system parachains (e.g. Rockmine, Contracts, BridgeHub).

Note: it doesn't seem like light client syncing is currently working (https://polkadot.js.org/apps/?rpc=light%3A%2F%2Fsubstrate-connect%2Frococo#/explorer) so would need to get this resolved too.

**Comment by Daanvdplas** [comment]
PR ready for rococo and rockmine. Rockmine's bootnodes are offline however and chainspec for rococo bridgehub is not present in cumulus repo.

What did the trick for syncing with Rococo was using the chainspec in smoldot repo (is an older one).

**Comment by stiiifff** [comment]
Closed by #23
